### PR TITLE
Extend support to gif

### PR DESCRIPTION
**Pull request by dieghernan**
Now chunked upload recognizes `gif` files. 

Also, `gif` under 5Mb are uploaded via the simple upload (i.e. as image, not chunked). This it done just for backwards compatiblity, as chunking of unanimated `gifs` is not supported (does anyone uses this? Well, anyway now it is supported). 

This PR would be added to https://github.com/ropensci/rtweet/pull/399

### CODE REVIEW

**Comment by tylermorganwall** [comment]
I recommend changing the `|` to `||` within the `if` statement to ensure we're always passing a non-vectorized boolean:

e.g. 

```
if(mediatype %in% c("jpg","jpeg", "png") || gif_no_chunked) {
```

**Comment by dieghernan** [comment]
> I recommend changing the `|` to `||` within the `if` statement to ensure we're always passing a non-vectorized boolean:
> 
> e.g.
> 
> ```
> if(mediatype %in% c("jpg","jpeg", "png") || gif_no_chunked) {
> ```

Done, thanks @tylermorganwall

**Comment by dieghernan** [comment]
You may want to add this last improvement @llrs

**Comment by dieghernan** [comment]
Not needed any more, incorporated via other commits.

Closing

**Pull request closed without merging**
